name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Paso 3: Iniciar sesión en Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: flaskacrcloud.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Paso 4: Construir y subir la imagen Docker al ACR
      - name: Build and Push Docker Image
        run: |
          docker build -t flaskacrcloud.azurecr.io/flask-backend:latest .
          docker push flaskacrcloud.azurecr.io/flask-backend:latest
      
      # Paso 5: Desplegar la imagen en Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: flask-web-app-cloud 
          images: flaskacrcloud.azurecr.io/flask-backend:latest
